import { Link } from "react-router-dom";

const PrivacyPolicy = () => {
  return (
    <div className="w-full relative pt-2">
      <h2 className="text-[24px] font-semibold leading-none">Privacy Policy</h2>
      <div className="w-full border my-5" />

      <div className="w-full h-[80vh] overflow-y-scroll">
        <p className="">
          giveXchange (“we,” “our,” or “us”) is committed to protecting your
          privacy. This Privacy Policy explains how your personal information is
          collected, used, and disclosed by giveXchange.
        </p>
        <p className="mt-2">
          This Privacy Policy applies to our website, and its associated
          subdomains (collectively, our “Service”) alongside our application,
          giveXchange. By accessing or using our Service, you signify that you
          have read, understood, and agree to our collection, storage, use, and
          disclosure of your personal information as described in this Privacy
          Policy and our Terms of Service.
        </p>

        <h3 className="font-semibold text-xl mt-4 mb-2">
          Definitions and key terms
        </h3>
        <p className="">
          To help explain things as clearly as possible in this Privacy Policy,
          every time any of these terms are referenced, are strictly defined as:
        </p>
        <ul className="space-y-2 mt-2">
          <li>
            <span className="font-semibold text-black">Cookie: </span>Small
            amount of data generated by a website and saved by your web browser.
            It is used to identify your browser, provide analytics, remember
            information about you such as your language preference or login
            information.
          </li>
          <li>
            <span className="font-semibold text-black">Company: </span>When this
            policy mentions “Company,” “we,” “us,” or “our,” it refers to
            giveXchange LLC, 5204 Mitchell St. Alexandria, VA 22312 that is
            responsible for your information under this Privacy Policy.
          </li>
          <li>
            <span className="font-semibold text-black">Country: </span>Where
            giveXchange or the owners/founders of giveXchange are based, in this
            case is United States.
          </li>
          <li>
            <span className="font-semibold text-black">Customer: </span>Refers
            to the company, organization or person that signs up to use the
            giveXchange Service to manage the relationships with your consumers
            or service users.
          </li>
          <li>
            <span className="font-semibold text-black">Device: </span>Any
            internet connected device such as a phone, tablet, computer or any
            other device that can be used to visit giveXchange and use the
            services.
          </li>
          <li>
            <span className="font-semibold text-black">IP address: </span>Every
            device connected to the Internet is assigned a number known as an
            Internet protocol (IP) address. These numbers are usually assigned
            in geographic blocks. An IP address can often be used to identify
            the location from which a device is connecting to the Internet.
          </li>
          <li>
            <span className="font-semibold text-black">Personnel: </span>Refers
            to those individuals who are employed by giveXchange or are under
            contract to perform a service on behalf of one of the parties.
          </li>
          <li>
            <span className="font-semibold text-black">Personal Data: </span>Any
            information that directly, indirectly, or in connection with other
            information — including a personal identification number — allows
            for the identification or identifiability of a natural person.
          </li>
          <li>
            <span className="font-semibold text-black">Service: </span>Refers to
            the service provided by giveXchange as described in the relative
            terms (if available) and on this platform.
          </li>
          <li>
            <span className="font-semibold text-black">
              Third-party service:{" "}
            </span>
            Refers to advertisers, contest sponsors, promotional and marketing
            partners, and others who provide our content or whose products or
            services we think may interest you.
          </li>
          <li>
            <span className="font-semibold text-black">Website: </span>
            giveXchange's site, which can be accessed via this URL:{" "}
            <Link to={`https://www.thegivexchange.com`} target="_blank">
              www.thegivexchange.com
            </Link>
          </li>
          <li>
            <span className="font-semibold text-black">You: </span>A person or
            entity that is registered with giveXchange to use the Services.
          </li>
        </ul>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
